import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/server";
import type { Types } from "cascade-cms-api";
import type { CascadeClient } from "../client.js";
import {
  registerCascadeTool,
  buildCascadeToolDescription,
  type CascadeDeps,
} from "./helper.js";
import {
  ToolBlockRuleSchema,
  updateToolBlockRules,
  type ToolBlockRule,
} from "../toolBlocks.js";
import { redactSecrets } from "../errors.js";

const SITE_REMOVAL_REASON =
  "Generated by protect_site_removal: block removal of all accessible Cascade sites";
const ROOT_FOLDER_REMOVAL_REASON =
  "Generated by protect_site_removal: block removal of site root folders";
const SITE_REMOVAL_SOURCE = "protect_site_removal:site";
const ROOT_FOLDER_REMOVAL_SOURCE = "protect_site_removal:root-folder";
const LEGACY_SITE_REMOVAL_SOURCE = "cascade_protect_site_removal:site";
const LEGACY_ROOT_FOLDER_REMOVAL_SOURCE = "cascade_protect_site_removal:root-folder";
const SITE_PROTECTION_TOOLS = ["remove", "move"];

const ToolBlocksRequestSchema = z
  .object({
    action: z
      .enum(["list", "add"])
      .describe("Action to perform against the local tool block repository."),
    rule: ToolBlockRuleSchema.optional().describe(
      "Rule to append when action is 'add'.",
    ),
  })
  .strict();

const ProtectSiteRemovalRequestSchema = z
  .object({})
  .strict();

export function registerToolBlockTool(
  server: McpServer,
  deps: CascadeDeps,
): void {
  registerCascadeTool(
    server,
    {
      name: "tool_blocks",
      title: "Manage blocked MCP tool calls",
      description: buildCascadeToolDescription(
        `List or add blocked MCP tool-call rules stored in the local JSON repository.

Use this tool when an agent should persist a guardrail that prevents selected tools from running against matching asset payloads. Rules require:
  - tools: exact MCP tool names to block, such as remove or edit.
  - url: one or more https Cascade CMS asset URLs at /entity/open.act. Each URL must include id and type.
  - type plus id/path for explicit selectors. URL selectors and explicit selectors may be combined.

Actions:
  - list: return the repository path and current rules.
  - add: append rule.

This management tool writes only the local repository. Because add can change guardrails, clients should require user approval before calling this tool. The blocked-call check runs before checked tools call Cascade or mutate local draft state.`,
      ),
      inputSchema: ToolBlocksRequestSchema,
      annotations: {
        readOnlyHint: false,
        destructiveHint: true,
        idempotentHint: false,
        openWorldHint: false,
      },
      handler: async (input) => runAction(input, deps),
    },
    deps,
  );
}

export function registerSiteRemovalProtectionTool(
  server: McpServer,
  client: CascadeClient,
  deps: CascadeDeps,
): void {
  registerCascadeTool(
    server,
    {
      name: "protect_site_removal",
      title: "Protect Cascade Sites From Removal Or Move",
      description: buildCascadeToolDescription(
        `Persist generated blocked-call rules that prevent removal or movement of accessible Cascade sites and their root folders.

The tool lists accessible sites, blocks remove and move by site id and site name/path, then tries to read each site's root folder at "/". Readable root folders are blocked by id, and path "/" is always included to block path-based root-folder removal or movement. Existing generated rules from this tool are replaced instead of duplicated; unrelated rules are preserved.

Returns a report with protected site count, protected root-folder id count, unreadable root folders, the block-store path, and final rule count.`,
      ),
      inputSchema: ProtectSiteRemovalRequestSchema,
      annotations: {
        readOnlyHint: false,
        destructiveHint: true,
        idempotentHint: true,
        openWorldHint: true,
      },
      handler: async () => protectSiteRemoval(client, deps),
    },
    deps,
  );
}

async function runAction(
  input: z.infer<typeof ToolBlocksRequestSchema>,
  deps: CascadeDeps,
): Promise<unknown> {
  if (!deps.toolBlockStore) {
    throw new Error("Tool block repository is not configured");
  }

  const store = deps.toolBlockStore;

  if (input.action === "list") {
    const rules = await store.read();
    return result(store.path, rules);
  }

  if (input.action === "add") {
    if (!input.rule) throw new Error("action 'add' requires rule");
    const next = await updateToolBlockRules(store, (current) => [...current, input.rule!]);
    return result(store.path, next);
  }

  throw new Error(`Unsupported tool block action: ${input.action}`);
}

function result(path: string, rules: ToolBlockRule[]): unknown {
  return {
    success: true,
    path,
    count: rules.length,
    rules,
  };
}

async function protectSiteRemoval(
  client: CascadeClient,
  deps: CascadeDeps,
): Promise<unknown> {
  if (!deps.toolBlockStore) {
    throw new Error("Tool block repository is not configured");
  }

  const store = deps.toolBlockStore;
  const sites = siteEntries(
    await client.listSites({} as unknown as Types.ListSitesRequest),
  );
  const rootFolders = await readRootFolders(client, sites);
  const rules = await updateToolBlockRules(store, (existing) => [
    ...preserveUserRules(existing),
    ...generatedRules(sites, rootFolders.ids),
  ]);

  return {
    success: true,
    path: store.path,
    count: rules.length,
    protectedSiteCount: sites.length,
    protectedRootFolderIdCount: rootFolders.ids.length,
    unreadableRootFolders: rootFolders.unreadable,
    rules,
  };
}

async function readRootFolders(
  client: CascadeClient,
  sites: Array<{ id: string; siteName: string }>,
): Promise<{
  ids: string[];
  unreadable: Array<{ siteId: string; siteName: string; message: string }>;
}> {
  const ids: string[] = [];
  const unreadable: Array<{ siteId: string; siteName: string; message: string }> = [];

  for (const site of sites) {
    try {
      const root = await client.read({
        identifier: {
          type: "folder",
          path: { path: "/", siteName: site.siteName },
        },
      } as unknown as Types.ReadRequest);
      const id = folderId(root);
      if (id) ids.push(id);
    } catch (err) {
      unreadable.push({
        siteId: site.id,
        siteName: site.siteName,
        message: errorMessage(err),
      });
    }
  }

  return { ids, unreadable };
}

function preserveUserRules(rules: readonly ToolBlockRule[]): ToolBlockRule[] {
  return rules.filter((rule) => !isGeneratedSiteRemovalRule(rule));
}

function isGeneratedSiteRemovalRule(rule: ToolBlockRule): boolean {
  return (
    rule.source === SITE_REMOVAL_SOURCE ||
    rule.source === ROOT_FOLDER_REMOVAL_SOURCE ||
    rule.source === LEGACY_SITE_REMOVAL_SOURCE ||
    rule.source === LEGACY_ROOT_FOLDER_REMOVAL_SOURCE
  );
}

function generatedRules(
  sites: Array<{ id: string; siteName: string }>,
  rootFolderIds: string[],
): ToolBlockRule[] {
  const rules: ToolBlockRule[] = [];
  if (sites.length > 0) {
    rules.push({
      type: "site",
      id: sites.map((site) => site.id),
      path: sites.map((site) => site.siteName),
      tools: SITE_PROTECTION_TOOLS,
      reason: SITE_REMOVAL_REASON,
      source: SITE_REMOVAL_SOURCE,
    });
  }
  rules.push({
    type: "folder",
    ...(rootFolderIds.length > 0 ? { id: rootFolderIds } : {}),
    path: "/",
    tools: SITE_PROTECTION_TOOLS,
    reason: ROOT_FOLDER_REMOVAL_REASON,
    source: ROOT_FOLDER_REMOVAL_SOURCE,
  });
  return rules;
}

function siteEntries(value: unknown): Array<{ id: string; siteName: string }> {
  const sites = isRecord(value) && Array.isArray(value.sites) ? value.sites : [];
  return sites.flatMap((site) => {
    if (!isRecord(site) || typeof site.id !== "string") return [];
    const path = isRecord(site.path) ? site.path : {};
    const siteName = typeof path.path === "string" ? path.path : undefined;
    return siteName ? [{ id: site.id, siteName }] : [];
  });
}

function folderId(value: unknown): string | undefined {
  if (!isRecord(value)) return undefined;
  if (isRecord(value.asset) && isRecord(value.asset.folder)) {
    return typeof value.asset.folder.id === "string"
      ? value.asset.folder.id
      : undefined;
  }
  if (isRecord(value.folder)) {
    return typeof value.folder.id === "string" ? value.folder.id : undefined;
  }
  return undefined;
}

function errorMessage(err: unknown): string {
  return redactSecrets(err instanceof Error ? err.message : String(err));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
